### ISSUE TITLE
Are you Focussing on Node.js?

### ISSUE THREAD

**Issue by nelsonic** [hwndept/framework-performance#1]
@hwndept is your aim to focus on Node.js or will you attempt to compare other runtimes? 💭 

Similar: https://hashrocket.com/blog/posts/websocket-shootout (_WebSocket focussed_)
https://github.com/hashrocket/websocket-shootout

**Comment by hwndept** [comment]
@nelsonic, I wanted to get some performance numbers for NodeJS frameworks, but It would interesting to include more runtimes. If you have time, feel free to create a PR with a runtime you are interested in.

Thanks for your interest!

**Comment by nelsonic** [comment]
@hwndept I'm Happy to create the versions for Hapi and Elixir.
Is your plan to store the _results_ of the benchmark in the "_root_" `README.md` file?
It's probably best if you run the benchmarks on _your_ laptop for consistency.
Or on a consistent AWS instance if you want to network latency to be considered. :wink:

**Comment by hwndept** [comment]
I will appreciate if you create app in elixir, hapi. Btw, for the last one I had created the issue #2.

> Is your plan to store the results of the benchmark in the "root" README.md file?

Haven't thought about it yet, I know exactly that if results are stored somewhere they all should be regenerated once new app has been added, since all the tests should be run in the same conditions/environment/period of time.

**Comment by hwndept** [comment]
@nelsonic, I had productive night/morning :) - I unified a bit approach please take a look on the #7, seems like we are ready now to write apps in different runtimes

**Comment by hwndept** [comment]
also I raised several issues:
- #2 - hapi;
- #3 - koa;
- #5 - goa;
- #6 - elixir;

**Comment by hwndept** [comment]
If you have any question, let me know, if not you may close this issue.

**Comment by nelsonic** [comment]
Closing in favour of issues dedicated to each runtime. 👍
